<# Pushing terraform code through CI/CD pipeline#>


trigger:
- main

  jobs:           
  - job: waitForValidation
    displayName: Wait for external validation 
     pool: server   
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:   
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
        notifyUsers: |
              approvalemail@test.com
        instructions: 'Please validate the build configuration and resume'
        onTimeout: 'resume'


  - job: activityonlinuxmachine
    pool: 
      vmImage: 'windows-latest' 


    steps:


      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        displayName: ‘Install Terraform 0.12.11’
        inputs:
        terraformVersion: 0.12.11


      - task: PowerShell@2
        displayName: "Run Terraform init"
        inputs:
        targetType: "inline"
        script: 'terraform init' 
        workingDirectory: "$(System.DefaultWorkingDirectory)/test"

      - task: PowerShell@2
        displayName: "Run Terraform plan"
        inputs:
        targetType: "inline"
        script: 'terraform plan' 
        workingDirectory: "$(System.DefaultWorkingDirectory)/test"   

      - task: PowerShell@2
        displayName: "Run Terraform apply"
        inputs:
        targetType: "inline"
        script: 'terraform apply -auto-approve' 
        workingDirectory: "$(System.DefaultWorkingDirectory)/test"    

          


